const roadmap = [
  {
    title: "HTML & CSS",
    status: "Completed",
    progress: 100,
  },
  {
    title: "JavaScript",
    status: "Completed",
    progress: 100,
  },
  {
    title: "React",
    status: "In Progress",
    progress: 65,
  },
  {
    title: "Next.js",
    status: "Upcoming",
    progress: 0,
  },
  {
    title: "AI Integration",
    status: "Locked",
    progress: 0,
  },
];

export default function RoadmapCard() {
  return (
    <div className="rounded-3xl bg-white p-8 shadow-sm">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">
            🧠 AI Learning Roadmap
          </h2>

          <p className="mt-2 text-gray-600">
            Personalized roadmap generated by AI.
          </p>
        </div>

        <span className="rounded-full bg-blue-100 px-4 py-2 text-sm font-semibold text-blue-600">
          68% Completed
        </span>
      </div>

      {/* Global Progress */}

      <div className="mt-8">
        <div className="h-3 overflow-hidden rounded-full bg-gray-200">
          <div className="h-full w-2/3 rounded-full bg-blue-600"></div>
        </div>
      </div>

      {/* Timeline */}

      <div className="mt-10 space-y-8">
        {roadmap.map((course, index) => (
          <div key={course.title} className="flex gap-5">
            {/* Timeline */}

            <div className="flex flex-col items-center">
              <div
                className={`flex h-10 w-10 items-center justify-center rounded-full text-white ${
                  course.status === "Completed"
                    ? "bg-green-500"
                    : course.status === "In Progress"
                    ? "bg-blue-600"
                    : course.status === "Upcoming"
                    ? "bg-gray-400"
                    : "bg-gray-300"
                }`}
              >
                {course.status === "Completed"
                  ? "✓"
                  : course.status === "In Progress"
                  ? "▶"
                  : "○"}
              </div>

              {index !== roadmap.length - 1 && (
                <div className="mt-2 h-16 w-1 bg-gray-200"></div>
              )}
            </div>

            {/* Content */}

            <div className="flex-1">
              <div className="flex items-center justify-between">
                <h3 className="text-xl font-semibold text-gray-900">
                  {course.title}
                </h3>

                <span
                  className={`text-sm font-semibold ${
                    course.status === "Completed"
                      ? "text-green-600"
                      : course.status === "In Progress"
                      ? "text-blue-600"
                      : "text-gray-500"
                  }`}
                >
                  {course.status}
                </span>
              </div>

              {course.progress > 0 && (
                <div className="mt-4">
                  <div className="h-2 overflow-hidden rounded-full bg-gray-200">
                    <div
                      className="h-full rounded-full bg-blue-600"
                      style={{ width: `${course.progress}%` }}
                    />
                  </div>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      <button className="mt-10 rounded-xl bg-black px-6 py-3 font-semibold text-white transition hover:opacity-90">
        Continue Learning
      </button>
    </div>
  );
}