export default function Solution() {
  return (
    <section className="bg-white py-32">
      <div className="mx-auto max-w-7xl px-6">

        <div className="text-center">

          <p className="text-sm font-semibold uppercase tracking-widest text-blue-600">
            The Solution
          </p>

          <h2 className="mt-4 text-5xl font-bold text-gray-900">
            Meet PeerLearn AI
          </h2>

          <p className="mx-auto mt-6 max-w-3xl text-xl text-gray-600">
            PeerLearn AI acts like an intelligent learning operating system.
            It builds your roadmap, connects you with the right teammates,
            guides every learning session, and keeps everyone accountable.
          </p>

        </div>

        <div className="mt-20 grid gap-8 md:grid-cols-2">

          <div className="rounded-3xl border border-gray-200 p-8 shadow-sm transition hover:shadow-lg">

            <div className="text-5xl">🧠</div>

            <h3 className="mt-4 text-xl font-semibold text-gray-900">
              Personalized AI Roadmap
            </h3>

            <p className="mt-4 text-gray-600">
              AI analyzes your goals and builds a personalized learning roadmap.
            </p>

          </div>

          <div className="rounded-3xl border border-gray-200 p-8 shadow-sm transition hover:shadow-lg">

            <div className="text-5xl">🤝</div>

            <h3 className="mt-4 text-xl font-semibold text-gray-900">
              Smart Team Matching
            </h3>

            <p className="mt-4 text-gray-600">
              Find study partners with similar skills, goals and availability.
            </p>

          </div>

          <div className="rounded-3xl border border-gray-200 p-8 shadow-sm transition hover:shadow-lg">

            <div className="text-5xl">📅</div>

            <h3 className="mt-4 text-xl font-semibold text-gray-900">
              AI Session Planner
            </h3>

            <p className="mt-4 text-gray-600">
              Every study session has a clear agenda generated by AI.
            </p>

          </div>

          <div className="rounded-3xl border border-gray-200 p-8 shadow-sm transition hover:shadow-lg">

            <div className="text-5xl">📊</div>

            <h3 className="mt-4 text-xl font-semibold text-gray-900">
              Progress Dashboard
            </h3>

            <p className="mt-4 text-gray-600">
              Track progress, achievements and team performance in one place.
            </p>

          </div>

        </div>

      </div>
    </section>
  );
}