import RoadmapCard from "@/components/dashboard/RoadmapCard";

export default function RoadmapPage() {
  return (
    <>
      <div className="mb-8">
        <h1 className="text-4xl font-bold text-gray-900">
          AI Learning Roadmap
        </h1>

        <p className="mt-2 text-gray-600">
          Follow your personalized learning journey generated by AI.
        </p>
      </div>

      <RoadmapCard />
    </>
  );
}